CREATE DATABASE TASKLIST;
USE TASKLIST;

CREATE TABLE PROJECT (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PROJECTNAME VARCHAR(64) NOT NULL,
DESCRIPTION VARCHAR(128)
);

CREATE TABLE TASK (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TASKNAME VARCHAR(128) NOT NULL,
COMPLETED BOOLEAN NOT NULL DEFAULT FALSE,
STARRED BOOLEAN NOT NULL DEFAULT FALSE,
PRIORITY INT NOT NULL DEFAULT 0,
STARTDATE DATE,
DUEDATE DATE,
PROJECTID INT,
NOTE VARCHAR(256),
FOREIGN KEY (PROJECTID) REFERENCES PROJECT(ID)
ON DELETE SET NULL
);

INSERT INTO PROJECT (PROJECTNAME) 
VALUES('INBOX');